'use client';

import { useEffect, useState } from 'react';
import AuthGate from './AuthGate';
import Icon from './Icon';
import Navbar from './Navbar';
import Sidebar from './Sidebar';
import { apiFetch } from '../lib/proxima-api';

function Settings() {
  const [connections, setConnections] = useState([]); const [metrics, setMetrics] = useState(null); const [message, setMessage] = useState(''); const [theme, setTheme] = useState('dark');
  const load = () => Promise.all([apiFetch('/api/integrations'), apiFetch('/api/metrics')]).then(([integrations, usage]) => { setConnections(integrations.items); setMetrics(usage); }).catch((err) => setMessage(err.message));
  useEffect(() => { load(); const savedTheme = window.localStorage.getItem('proxima_theme') || 'dark'; setTheme(savedTheme); document.documentElement.dataset.theme = savedTheme; const params = new URLSearchParams(window.location.search); setMessage(params.get('connected') ? `${params.get('connected')} connected successfully.` : params.get('error') || ''); }, []);
  const toggleTheme = () => { const next = theme === 'dark' ? 'light' : 'dark'; setTheme(next); window.localStorage.setItem('proxima_theme', next); document.documentElement.dataset.theme = next; };
  const connect = async (tool) => { try { window.location.assign((await apiFetch(`/api/integrations/${tool}/connect`, { method: 'POST', body: '{}' })).authorizationUrl); } catch (err) { setMessage(err.message); } };
  const disconnect = async (tool) => { try { await apiFetch(`/api/integrations/${tool}`, { method: 'DELETE' }); await load(); } catch (err) { setMessage(err.message); } };
  return <><div className="bg-grid" /><main className="shell"><Navbar title="Settings" /><div className="workspace-page"><Sidebar /><section className="panel page-content"><div className="settings-heading"><div><p className="eyebrow with-icon"><Icon name="plug" size={14} /> Connections</p><h1>Tool registry</h1></div><button className="secondary with-icon" onClick={toggleTheme}><Icon name={theme === 'dark' ? 'spark' : 'moon'} size={15} /> Use {theme === 'dark' ? 'light' : 'dark'} mode</button></div><p className="lede">OAuth tokens are encrypted on the backend. Connection only succeeds once the provider credentials and callback URL are configured.</p>{message ? <p className="connection-message"><Icon name="info" size={15} /> {message}</p> : null}<div className="usage-grid">{[['Workflows', metrics?.total, 'workflow'], ['Running', metrics?.running, 'activity'], ['Awaiting approval', metrics?.waitingApproval, 'shield'], ['Completed', metrics?.completed, 'checkCircle']].map(([label, value, icon]) => <div className="detail-metric" key={label}><span className="metric-label with-icon"><Icon name={icon} size={14} /> {label}</span><strong className="metric-value">{value ?? 0}</strong></div>)}</div><div className="connection-grid">{connections.map((item) => <article className="connection-card" key={item.name}><div className="with-icon"><span className="section-icon"><Icon name={item.connected ? 'link' : 'plug'} /></span><div><strong>{item.label}</strong><p className={item.connected ? 'connected' : 'muted'}>{item.connected ? 'Connected' : item.connectionRequired && item.configured ? 'Ready to connect' : item.connectionRequired ? 'Credentials required' : item.configured ? 'Server credentials configured' : 'Credentials required'}</p></div></div><div className="action-row">{item.connectionRequired ? item.connected ? <button className="secondary with-icon" onClick={() => disconnect(item.name)}><Icon name="x" size={15} /> Disconnect</button> : <button className="primary with-icon" disabled={!item.configured} onClick={() => connect(item.name)}><Icon name="link" size={15} /> Connect OAuth</button> : <button className="secondary with-icon" disabled><Icon name="lock" size={15} /> Server-managed</button>}</div></article>)}</div></section></div></main></>;
}
export default function SettingsPanel() { return <AuthGate><Settings /></AuthGate>; }
