'use client';

import { useState } from 'react';
import AuthGate from './AuthGate';
import Navbar from './Navbar';
import Sidebar from './Sidebar';
import PlatformSelector from './PlatformSelector';
import SocialPostCard from './SocialPostCard';
import { apiFetch } from '../lib/proxima-api';

const limits = { twitter: 280, linkedin: 3000, facebook: 63206, whatsapp: 4096 };
function Composer() {
  const [goal, setGoal] = useState('Launch our v2 on all social channels'); const [platforms, setPlatforms] = useState(Object.keys(limits)); const [withImage, setWithImage] = useState(true); const [imagePrompt, setImagePrompt] = useState('A clean, futuristic launch image for Proxima v2, deep-space background, cyan and purple light'); const [drafts, setDrafts] = useState({}); const [image, setImage] = useState(null); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [scheduledFor, setScheduledFor] = useState('');
  const generate = async () => { setBusy(true); setMessage(''); try { const result = await apiFetch('/api/social/draft', { method: 'POST', body: JSON.stringify({ goal, platforms, generate_image: withImage && !image, image_prompt: imagePrompt }) }); setDrafts(result.drafts); if (result.image) setImage(result.image); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  const upload = async (event) => { const file = event.target.files?.[0]; if (!file) return; setBusy(true); setMessage(''); try { const form = new FormData(); form.append('file', file); const token = window.localStorage.getItem('proxima_token'); const response = await fetch('/api/social/upload', { method: 'POST', headers: token ? { Authorization: `Bearer ${token}` } : {}, body: form }); const result = await response.json(); if (!response.ok) throw new Error(result.detail || result.error || 'Upload failed.'); setImage(result); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  const publish = async () => { setBusy(true); setMessage(''); try { const post = await apiFetch('/api/social/publish', { method: 'POST', body: JSON.stringify({ content: drafts, platforms, image_id: image?.id, scheduled_for: scheduledFor || null }) }); setMessage(post.status === 'scheduled' ? 'Post scheduled for every selected platform.' : 'Post saved for approval.'); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  return <><div className="bg-grid" /><main className="shell"><Navbar title="Social Media Hub" /><div className="workspace-page"><Sidebar /><section className="panel page-content"><p className="eyebrow">AI content studio</p><h1>Draft, design, and approve social campaigns</h1><p className="lede">Generate platform-aware copy, upload your own campaign asset, or generate one with the configured AI image model. Publishing remains approval-first.</p><label className="field"><span>Campaign goal</span><textarea value={goal} onChange={(event) => setGoal(event.target.value)} rows={3} /></label><PlatformSelector selected={platforms} onChange={setPlatforms} /><div className="social-controls"><label><input type="checkbox" checked={withImage} onChange={(event) => setWithImage(event.target.checked)} /> Generate AI image</label><label className="field"><span>Image prompt</span><input value={imagePrompt} onChange={(event) => setImagePrompt(event.target.value)} disabled={!withImage} /></label><label className="ghost upload-control">Upload image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload} hidden /></label></div><div className="action-row"><button className="primary" disabled={busy || !goal.trim() || !platforms.length} onClick={generate}>Generate campaign</button><label className="field schedule-field"><span>Optional schedule</span><input type="datetime-local" value={scheduledFor} onChange={(event) => setScheduledFor(event.target.value)} /></label><button className="secondary" disabled={busy || !Object.keys(drafts).length} onClick={publish}>{scheduledFor ? 'Schedule selected posts' : 'Send for approval'}</button></div>{message ? <p className="connection-message">{message}</p> : null}<div className="social-hub-grid">{Object.entries(drafts).map(([platform, text]) => <SocialPostCard key={platform} platform={platform} text={text} limit={limits[platform]} image={image} onChange={(key, value) => setDrafts((current) => ({ ...current, [key]: value }))} />)}</div></section></div></main></>;
}
export default function SocialHub() { return <AuthGate><Composer /></AuthGate>; }
